@startuml
title Session start
actor Customer
participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "Webservice" #abcaff
participant "Commerce Insurance" #abcaff
participant "Commerce Customer" #abcaff
participant "2019" #abcaff
participant "Direct Billing Backend" #c3ffcd
database "Redis" #yellow
database "Mysql" #fdda14

autonumber
Customer -> FE:Customer opens our website
FE -> "Direct Billing Bundle UI":Load & initialize UI bundle
"Direct Billing Bundle UI" --> FE:Response
FE -> "Webservice":POST /insurance/session-start
"Webservice" -> "Commerce Insurance":POST /session-start
"Commerce Insurance" -> "Redis":Get the session status
alt Session has started
    "Commerce Insurance" -> "Mysql":Insert a visit log
    "Commerce Insurance" --> "Webservice":Response
    "Webservice" --> FE:Response
else Session has not started
     alt "If it is a login customer"
        "Commerce Insurance" -> "Commerce Customer":GET /users/{user-id}
        "Commerce Customer" --> "Commerce Insurance":Response
     end
     alt "If the cart is not empty"
        "Commerce Insurance" -> 2019:POST /cart
        2019 --> "Commerce Insurance":Response
     end
     "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/start
     "Direct Billing Backend" --> "Commerce Insurance":Response
     alt "If the response include insurance details"
        "Commerce Insurance" -> "Mysql":Insert the insurance details
     end
     "Commerce Insurance" -> "Mysql":Insert a visit log
     "Commerce Insurance" --> "Webservice":Response
     "Webservice" --> FE:Response
end

"Direct Billing Bundle UI" -> FE: Hook function getCustomer
alt If it is a guest customer
    FE --> "Direct Billing Bundle UI":Response guest customer info
else If it is a login customer
    FE -> "Webservice":GET /users/{user-id}
    "Webservice" -> "Commerce Customer":GET /users/{user-id}
    "Commerce Customer" --> "Webservice":Response
    "Webservice" --> FE:Response
    FE --> "Direct Billing Bundle UI":Response login customer info
end

@enduml

