@startuml
title Session start
actor Customer
participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "Webservice" #abcaff
participant "Commerce Insurance" #abcaff
participant "Commerce Customer" #abcaff
participant "2019" #abcaff
participant "Direct Billing Backend" #c3ffcd
database "Redis" #yellow
database "Mysql" #fdda14

autonumber
Customer -> FE:Customer opens our website
FE -> "Direct Billing Bundle UI":Load & initialize UI bundle
"Direct Billing Bundle UI" --> FE:Response
FE -> "Webservice":POST /insurance/session-start
"Webservice" -> "Commerce Insurance":POST /session-start
"Commerce Insurance" -> "Redis":Get the session status
"Redis" --> "Commerce Insurance":Response
alt If the session cache is not empty
    "Commerce Insurance" -> "Mysql":Refresh the expire time of session
    "Commerce Insurance" --> "Webservice":Response
    "Webservice" --> FE:Response
else If the session cache is empty

'    Start verify whether the previous account has ended the session
    alt If current customer is logged in
        "Commerce Insurance" -> "Mysql":Get the guest customer's active session
        "Mysql" --> "Commerce Insurance":Response
        alt If the session is not empty
            "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/end
            "Direct Billing Backend" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Mysql":Update the guest customer's active session to inactive
            "Mysql" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Redis":Delete the guest customer's active session
            "Redis" --> "Commerce Insurance":Response
        end
    else If current customer is not logged in
        "Commerce Insurance" -> "Mysql":Get the previously logged-in customer's active session
        "Mysql" --> "Commerce Insurance":Response
        alt If the session is not empty
            "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/end
            "Direct Billing Backend" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Mysql":Update the logged-in customer's active session to inactive
            "Mysql" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Redis":Delete the logged-in customer's active session
            "Redis" --> "Commerce Insurance":Response
        end
    end
'    End verify whether the previous account has ended the session

    "Commerce Insurance" -> "Mysql":Get the current customer's <font color=red>active session
    "Mysql" --> "Commerce Insurance":Response
    alt If the session is empty
        alt "If it is a logged-in customer"
           "Commerce Insurance" -> "Commerce Customer":GET /users/{user-id}
           "Commerce Customer" --> "Commerce Insurance":response
        end
        alt "If the cart is not empty"
           "Commerce Insurance" -> 2019:POST /cart
           2019 --> "Commerce Insurance":response
        end
        "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/start
        "Direct Billing Backend" --> "Commerce Insurance":Response
        alt "If the response include insurance details"
            "Commerce Insurance" -> "Mysql":Insert the insurance details
        end
        "Commerce Insurance" -> "Mysql":Insert a new session
        "Mysql" --> "Commerce Insurance":Response
        "Commerce Insurance" -> "Redis":Set session status
        "Redis" --> "Commerce Insurance":Response
    else If the session is not empty
        alt If the session is expired
            "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/end
            "Direct Billing Backend" --> "Commerce Insurance":Response
            alt "If it is a logged-in customer"
               "Commerce Insurance" -> "Commerce Customer":GET /users/{user-id}
               "Commerce Customer" --> "Commerce Insurance":response
            end
            alt "If the cart is not empty"
               "Commerce Insurance" -> 2019:POST /cart
               2019 --> "Commerce Insurance":response
            end
            "Commerce Insurance" -> "Direct Billing Backend":POST /commerce-session/start
            "Direct Billing Backend" --> "Commerce Insurance":Response
            alt "If the response include insurance details"
                "Commerce Insurance" -> "Mysql":Insert the insurance details
            end
            "Commerce Insurance" -> "Mysql":Insert a new session
            "Mysql" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Redis":Set session status
            "Redis" --> "Commerce Insurance":Response
        else If the session is not expired
            "Commerce Insurance" -> "Mysql":Refresh the expire time of session
            "Mysql" --> "Commerce Insurance":Response
            "Commerce Insurance" -> "Redis":Set session status
            "Redis" --> "Commerce Insurance":Response
        end
    end
    "Commerce Insurance" --> "Webservice":Response

     "Webservice" --> FE:Response
end

"Direct Billing Bundle UI" -> FE: Hook function getCustomer
alt If it is a guest customer
    FE --> "Direct Billing Bundle UI":Response guest customer info
else If it is a login customer
    FE -> "Webservice":GET /users/{user-id}
    "Webservice" -> "Commerce Customer":GET /users/{user-id}
    "Commerce Customer" --> "Webservice":Response
    "Webservice" --> FE:Response
    FE --> "Direct Billing Bundle UI":Response login customer info
end

@enduml

