@startuml
title User clicks Apply insurance
actor Customer
participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "2019" #abcaff
participant "Webservice" #abcaff
participant "Commerce Insurance" #abcaff
participant "Commerce Customer" #abcaff
participant "Direct Billing Backend" #c3ffcd
database "Redis" #yellow
database "Mysql" #fdda14

autonumber
Customer -> FE:Update the products of cart
FE -> 2019:POST /cart
'note right
'Step 2 and step 3 at the same time
'end note
FE -> "Direct Billing Bundle UI":Trigger onCartBundleChange event
2019 -> 2019:Update the cart
2019 -> "Commerce Insurance":POST /carts/{cart-id}/products
"Commerce Insurance" -> "Direct Billing Backend":POST /carts/{cart-id}/products
"Direct Billing Backend" --> "Commerce Insurance":<font color=red>Response {}
"Commerce Insurance" --> 2019:Response
"2019" -> FE:Response
FE -> FE:Refresh the product list and total price on cart page. Refresh quick cart.

@enduml

