@startuml
title Customer places order successfully but failed to notify the Direct Billing
actor Customer
participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "2019" #abcaff
participant "Commerce Insurance" #abcaff
participant "Direct Billing Backend" #c3ffcd
database "Redis" #yellow
database "Mysql" #fdda14

autonumber
Customer -> FE:Click the "Confirm and Pay"
FE -> 2019:GET /payment/check
2019 -> "Commerce Insurance":POST /carts/update-status ORDER_PLACE_STARTED
"Commerce Insurance" -> "Direct Billing Backend":POST /carts/{{cart-id}}/update-status ORDER_PLACE_STARTED
"Direct Billing Backend" --> "Commerce Insurance":Response insurance details
"Commerce Insurance" -> "Mysql":Get the insurance details
"Mysql" --> "Commerce Insurance":Response
"Commerce Insurance" --> "Commerce Insurance" :Compare the returned data with the insurance details in the database
"Commerce Insurance"  --> 2019:Response insurance details

2019 --> 2019:Process payment
2019 -> "Direct Billing Backend":POST /carts/{{cart-id}}/update-status ORDER_PLACE_PLACED
"Direct Billing Backend" --> 2019:Response
alt Response includes error message
    2019 -> "Redis":Push the order number to the queue
    Redis -> "Direct Billing Backend":Response
end
2019 -> FE:Redirect to thankyou page
FE -> "Direct Billing Bundle UI":Trigger onOrderComplete event <font color=red>


@enduml

