@startuml
title Customer clicks Insurance different product
actor Customer
participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "2019" #abcaff
participant "Webservice" #abcaff
participant "Commerce Insurance" #abcaff
participant "Commerce Customer" #abcaff
participant "Direct Billing Backend" #c3ffcd
database "Redis" #yellow
database "Mysql" #fdda14

autonumber
Customer -> "Direct Billing Bundle UI":Customer clicks "Insure Different Product" and select another product to apply insurance
"Direct Billing Bundle UI" -> "Direct Billing Backend":POST /claim-records/{id}/select-claimable
"Direct Billing Backend" -> "Webservice":POST /update-insurance-details
"Webservice" -> "Commerce Insurance":POST /quote/update-details
"Commerce Insurance" -> "Mysql":Insert insurance details
"Mysql" --> "Commerce Insurance":Response
"Commerce Insurance" --> "Webservice":Response
"Webservice" --> "Direct Billing Backend":Response
"Direct Billing Backend" --> "Direct Billing Bundle UI":Response
"Direct Billing Bundle UI" -> FE:Hook function refreshCart
FE -> 2019:GET /cart
2019 --> FE:Response
FE -> FE:Update the discount price on cart page and quick cart
@enduml

