@startuml

participant FE #abcaff
participant "Direct Billing Bundle UI" #c3ffcd
participant "Webservice" #abcaff
participant "Commerce Insurance" #abcaff
database "Redis" #yellow

autonumber
FE -> "Webservice":POST /insurances/toggle
"Webservice" -> "Commerce Insurance":POST /insurances/toggle
"Commerce Insurance" -> "Redis":Get the circuit breaker status
"Redis" --> "Commerce Insurance":Response
"Commerce Insurance" --> "Webservice":Response
Webservice --> FE:Response circuit breaker error message

alt Circuit breaker is open
    FE -> FE:Don't load EyeMed JS
else
     FE -> "Direct Billing Bundle UI":Load EyeMed JS
     "Direct Billing Bundle UI" --> FE:Response
end


@enduml

