@startuml
'https://plantuml.com/class-diagram


together {
interface SessionInterface
interface CartInterface
interface OrderInterface
interface QuoteDetailInterface
}
together {
class SessionService
class CartService
class OrderService
class QuoteDetailService
}

together {
class DirectBilling
class Fake
}

abstract class AbstractInsuranceService
interface StrategyInterface
interface DirectBillingInsuranceInterface


'继承
DirectBillingInsuranceInterface --|> SessionInterface
DirectBillingInsuranceInterface --|> CartInterface
DirectBillingInsuranceInterface --|> OrderInterface
DirectBillingInsuranceInterface --|> QuoteDetailInterface

DirectBilling ..|> DirectBillingInsuranceInterface
Fake ..|> DirectBillingInsuranceInterface


'实现
SessionService --> SessionInterface
CartService --> CartInterface
OrderService --> OrderInterface
QuoteDetailService --> QuoteDetailInterface

AbstractInsuranceService --> StrategyInterface
AbstractInsuranceService --> DirectBillingInsuranceInterface

SessionService --|> AbstractInsuranceService
CartService --|> AbstractInsuranceService
OrderService --|> AbstractInsuranceService
QuoteDetailService --|> AbstractInsuranceService

'方法定义
SessionInterface : start()
SessionInterface : end()

CartInterface : formatProducts()
CartInterface : syncProducts()
CartInterface : syncStatus()

QuoteDetailInterface : syncDetails()
QuoteDetailInterface : getDetails()

OrderInterface : syncOrderStatus()

AbstractInsuranceService : getStrategy()





@enduml