@startuml
title Guest User ID Generation Flow

actor Customer
participant Nextjs #abcaff
participant "www" #abcaff
participant "Cookie" as Cookie #yellow

autonumber

Customer -> Nextjs: Visit page
note right of Cookie
  Stored in browser, accessible to both FE and BE
end note
Nextjs -> Cookie: Get guest user id
Cookie --> Nextjs: Response
alt Guest user id is **empty**
    Nextjs -> Nextjs: Generate new guest user id
    Nextjs -> Cookie: Save guest user id
    Cookie --> Nextjs: Response
end

Nextjs -> www: GET /system/visitor-analysis
www -> Cookie: Get guest user id
Cookie --> www: Response
alt Guest user id is **empty**
    www -> www: Generate new guest user id
    www -> Cookie: Save guest user id
    Cookie --> www: Response
else
    www --> Nextjs: Response
end


@enduml
