@startuml
'https://plantuml.com/activity-diagram-beta

start
:Get the cronjob status from redis;
if (Cron job is running?) then (yes)
else (no)
:Set cron job status to 1 in redis;
repeat
:Find sessions with status=1 and expire_time < now (limit 100);
    :Concurrent processing session;
    :Check if the session has already ended;
    if (Session is not ended?) then (yes)
        :Call session end API;
        if (API call successful?) then (yes)
            :Update session status to 0;
        else (no)
            :Log error message;
        endif
    endif
repeat while (more sessions?)
:Remove cronjob status in redis;
endif

stop

@enduml
